name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create Conda environment
      run: |
        conda create --name d2l python=3.9 -y
    - name: Activate Conda environment and install dependencies
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate d2l
        pip install torch==1.12.0
        pip install torchvision==0.13.0
        pip install d2l==0.17.6
    - name: Lint with flake8
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate d2l
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate d2l
        conda install pytest
        pytest
